server:
    port: 9999
spring:
    application:
        name: xzjcjw
    datasource:
        name: xzjcjw
        type: com.alibaba.druid.pool.DruidDataSource
#        url: jdbc:log4jdbc:mysql://localhost:3306/sakila?userUnicode=true&characterEncoding=utf-8&useSSL=false
        url: jdbc:mysql://127.0.0.1:3306/sakila?userUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root
#        driver-class-name: net.sf.log4jdbc.DriverSpy
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 20
        initialSize: 20
        maxWait: 60000
        minIdle: 20
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,log4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000